SELECT * FROM CRUSH WHERE YEAR>2016;

SELCT CURRENT_CRUSH  FROM CRUSH WHERE LOVE = 1;

DELETE EXS FROM LIFE WHERE EX_ACTIVE =1;

INSERT INTO LIFE VALUES  (SELECT CRUSH_NAME,CRUSH_NATIVE,LOVE_CALCULATOR FROM CRUSH WHERE CRUSH =1);
